name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.8
  - snowflake-snowpark-python
  - pip
  - pandas
  - pip:
    # Snowflake
    - snowflake-cli-labs==0.2.9
